lavender: Add 3.0 and 4.0 IMapper instance to manifest
ERROR: files are incompatible: Device manifest and framework compatibility matrix are incompatible: HALs incompatible. Matrix level = 4. Manifest level = 4. The following requirements are not met:
android.hardware.graphics.mapper:
    required:
        @2.1::IMapper/default OR
        @3.0::IMapper/default OR
        @4.0::IMapper/default
    provided:

Signed-off-by: Shridhan Varadkar <shridhan98@gmail.com>